#! /bin/sh

killall sxhkd
sxhkd &

killall ibus-daemon
ibus-daemon -drx

setxkbmap pl
killall redshift
redshift -l 50.0614:19.9365 &

picom --config ~/.config/picom.conf --experimental-backends &
~/.config/polybar/launch.sh & 
feh --bg-fill ~/current-wallpaper.jpg

bspc monitor DP-2 -d 1 2 3 4 5  
bspc monitor HDMI-0  -d 6 7 8 9 0 

bspc config border_width 3
bspc config window_gap 2
bspc config border_radius	0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#98971a'
