#! /bin/sh

sxhkd &

~/.config/polybar/launch.sh & 
feh --bg-fill ~/wallpaper.png
picom --config ~/.config/picom.conf &

bspc monitor DP-2 -d 1 2 3 4 5 6 7 
bspc monitor HDMI-0  -d 8 9 10 11 12 13 

bspc config border_width         0
bspc config window_gap          20
bspc config border_radius	5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
